# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='hashed_pw',
        ),
    ]
